import re
from modules import Evaluator
from textstat import smog_index
import json, subprocess
from pathlib import Path
import spacy

class ConstructivenessEvaluator(Evaluator):
    discourse_connectives = {
        "in case",
        "accordingly",
        "additionally",
        "after",
        "after this",
        "afterward",
        "all in all",
        "also",
        "alternatively",
        "although",
        "and",
        "anyway",
        "as",
        "as a result",
        "as an alternative",
        "as if",
        "as long as",
        "as soon as",
        "as though",
        "as well",
        "assuming that",
        "at any rate",
        "at last",
        "at least",
        "at that",
        "because",
        "before",
        "before and after",
        "besides",
        "but",
        "by comparison",
        "by contrast",
        "by then",
        "consequently",
        "considering that",
        "conversely",
        "earlier",
        "either",
        "either..or",
        "else",
        "except",
        "except in that",
        "except insofar as",
        "finally",
        "for",
        "for example",
        "for instance",
        "from then on",
        "further",
        "furthermore",
        "given that",
        "hence",
        "however",
        "if",
        "if and when",
        "if ever",
        "if only",
        "if..then",
        "immediately",
        "in addition",
        "in conclusion",
        "in contrast",
        "in fact",
        "in other words",
        "in particular",
        "in short",
        "in so doing",
        "in sum",
        "in that",
        "in that case",
        "in the end",
        "in turn",
        "indeed",
        "insofar as",
        "instantly",
        "instead",
        "it follows that",
        "just as",
        "later",
        "lest",
        "likewise",
        "meantime",
        "meanwhile",
        "moreover",
        "much as",
        "neither..nor",
        "nevertheless",
        "next",
        "nonetheless",
        "nor",
        "now that",
        "on condition that",
        "on the contrary",
        "on the grounds that",
        "on the one hand..on the other hand",
        "on the other hand",
        "once",
        "or",
        "or rather",
        "otherwise",
        "overall",
        "plainly",
        "plus",
        "previously",
        "rather",
        "regardless",
        "seeing as",
        "separately",
        "similarly",
        "simultaneously",
        "since",
        "so",
        "so that",
        "specifically",
        "still",
        "summing up",
        "supposing",
        "supposing that",
        "that is",
        "that is to say",
        "the way",
        "then",
        "thereafter",
        "thereby",
        "therefore",
        "though",
        "thus",
        "till",
        "to conclude",
        "to recap",
        "too",
        "ultimately",
        "unless",
        "until",
        "when",
        "when and if",
        "whereas",
        "while",
        "yet",
    }

    stance_adverbials = {
        "actually",
        "admittedly",
        "alternatively",
        "amazingly",
        "apparently",
        "arguably",
        "astonishingly",
        "certainly",
        "confidentially",
        "conveniently",
        "decidedly",
        "definitely",
        "disturbingly",
        "evidently",
        "figuratively",
        "fortunately",
        "frankly",
        "generally",
        "honestly",
        "hopefully",
        "incontestably",
        "incontrovertibly",
        "indeed",
        "inevitably",
        "ironically",
        "mainly",
        "maybe",
        "only",
        "paradoxically",
        "perhaps",
        "predictably",
        "probably",
        "radically",
        "regrettably",
        "reportedly",
        "reputedly",
        "sensibly",
        "seriously",
        "strictly",
        "supposedly",
        "surprisingly",
        "truly",
        "truthfully",
        "typically",
        "undeniably",
        "undoubtedly",
        "unfortunately",
        "wisely",
    }

    reasoning_lemmas = {
        "advance", "rationalize", "necessitate", "reason", "infer", "indicate", "establish", "posit", "substantiate", "account", "illustrate", "produce", "deduce", "induce", "reveal", "dictate", "contend", "assert", "clarify", "lead", "imply", "elucidate", "verify", "corroborate",
        "note",
        "accept",
        "accuse",
        "acknowledge",
        "address",
        "admit",
        "advise",
        "affect",
        "afford",
        "agree",
        "allow",
        "announce",
        "answer",
        "appeal",
        "appreciate",
        "approve",
        "argue",
        "ask",
        "assess",
        "assist",
        "assume",
        "assure",
        "bear",
        "believe",
        "blame",
        "bother",
        "calculate",
        "call",
        "care",
        "cause",
        "celebrate",
        "challenge",
        "choose",
        "claim",
        "compare",
        "complain",
        "conclude",
        "confirm",
        "consider",
        "consult",
        "convince",
        "count",
        "dare",
        "decide",
        "declare",
        "demand",
        "deny",
        "describe",
        "deserve",
        "detect",
        "determine",
        "discover",
        "discuss",
        "dismiss",
        "distinguish",
        "doubt",
        "emphasize",
        "enable",
        "encourage",
        "enjoy",
        "ensure",
        "examine",
        "excuse",
        "expect",
        "experience",
        "explain",
        "express",
        "face",
        "fear",
        "feel",
        "find",
        "force",
        "forget",
        "forgive",
        "guarantee",
        "guess",
        "hate",
        "hear",
        "help",
        "hope",
        "identify",
        "ignore",
        "imagine",
        "impress",
        "influence",
        "inform",
        "insist",
        "intend",
        "interpret",
        "invite",
        "judge",
        "justify",
        "know",
        "learn",
        "let",
        "like",
        "listen",
        "love",
        "mean",
        "mention",
        "mind",
        "miss",
        "need",
        "notice",
        "observe",
        "offer",
        "perceive",
        "permit",
        "persuade",
        "phone",
        "plan",
        "pray",
        "predict",
        "prefer",
        "pretend",
        "prevent",
        "promise",
        "propose",
        "prove",
        "publish",
        "question",
        "quote",
        "read",
        "realice",
        "recall",
        "reckon",
        "recognize",
        "recommend",
        "regard",
        "remark",
        "remember",
        "remind",
        "reply",
        "report",
        "require",
        "respond",
        "satisfy",
        "say",
        "see",
        "shout",
        "sign",
        "sing",
        "solve",
        "speak",
        "specify",
        "state",
        "study",
        "suffer",
        "suggest",
        "suppose",
        "suspect",
        "swear",
        "talk",
        "teach",
        "tell",
        "thank",
        "think",
        "threaten",
        "trust",
        "understand",
        "urge",
        "want",
        "warn",
        "welcome",
        "whisper",
        "wish",
        "wonder",
        "worry",
        "write",
    }
    
    impolite_features = {"Swearing", "Bare.Command", "Negative.Emotion", "Informal.Title"}

    def __init__(self):
        super().__init__(name="Constructiveness")
        self.nlp = spacy.load("en_core_web_md")

    def evaluate_utterance(self, text: str) -> dict:
        word_count = len(text.split())
        readability = smog_index(text)

        # Computing politeness features with R script (annoying)
        r_script = Path(__file__).resolve().parent.parent / "r" / "politeness_eval.R"
        cmd = ["Rscript", str(r_script), text]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0 or not result.stdout.strip():
            print("R STDERR:\n", result.stderr)
            print("R STDOUT:\n", result.stdout)
            raise RuntimeError(f"Rscript failed (exit {result.returncode})")
        politeness_dict = json.loads(result.stdout)
        impolite_features = {feature: politeness_dict[feature] for feature in self.impolite_features}
        polite_features = {feature: politeness_dict[feature] for feature in politeness_dict if feature not in self.impolite_features}

        doc = self.nlp(text.lower())
        num_entities = len(doc.ents)

        argumentative_features = {
            "discourse_connectives": 0,
            "stance_adverbials": 0,
            "reasoning_verbs": 0,
            "modals": 0,
            "full_root_clauses": 0,
            "partial_root_clauses": 0
        }

        lowered = text.lower()

        for dc in self.discourse_connectives:
            if re.search(rf"\b{re.escape(dc)}\b", lowered):
                argumentative_features["discourse_connectives"] += 1

        for stance_adverbial in self.stance_adverbials:
            if re.search(rf"\b{re.escape(stance_adverbial)}\b", lowered):
                argumentative_features["stance_adverbials"] += 1

        for token in doc:
            if token.pos_ == "VERB" and token.lemma_.lower() in self.reasoning_lemmas:
                argumentative_features["reasoning_verbs"] += 1
            if token.tag_ == "MD":
                argumentative_features["modals"] += 1
            if token.dep_ == "ROOT" and token.pos_ == "VERB":
                if token.lemma_.lower() in self.reasoning_lemmas:
                    has_subject = any(child.dep_ == "nsubj" for child in token.children)
                    has_complement = any(
                        child.dep_ in ["ccomp", "xcomp"]
                        for child in token.children
                    )
                    if has_subject:
                        if has_complement:
                            argumentative_features["full_root_clauses"] += 1
                        else:
                            argumentative_features["partial_root_clauses"] += 1

        return {
            "word_count": word_count,
            "readability": readability,
            "polite_features_count": sum(polite_features.values()),
            "impolite_features_count": sum(impolite_features.values()),
            "named_entities_count": num_entities,
            "argumentative_features": sum(argumentative_features.values())
        }