discourse_me = {
    "and", "or", "for", "as", "if", "so", "when", "but",
    "one", "then", "now", "after", "before", "here", "never", "since", 
    "always", "during", "later", "often", "once", "sometimes", "soon", 
    "usually", "earlier", "recently", "quickly", "first", "suddenly", 
    "immediately", "shortly", "formerly", "frequently", "occasionally", 
    "rarely", "seldom", "nowadays", "eventually", "ultimately", "presently",
    "directly", "initially", "originally", "subsequently", "currently",
    "momentarily", "lately", "continually", "constantly", "regularly",
    "intermittently", "temporarily", "permanently", "instantly", "promptly",
    "all of the time", "for much of the time", "in a year's time", 
    "it was at this time", "for long periods of time", "in the fullness of time",
    "in the same time", "it is about time", "after a short time", "to top it all",
    "time and time again", "there was a time", "now and again", "and all the time",
    "following", "until", "finally", "previously", "next", "last", "lastly",
    "in a very short time", "in a fortnight's time", "last of all", "time to move on",
    "by the by", "as a final point", "as of yet", "afore", "not long ago",
    "second", "third", "firstly", "secondly", "thirdly",
    "in the first place", "in the second place", "in the next place",
    "for another thing", "afterward", "the latter", "the former", 
    "second of all",
    "because", "because of", "due to", "owing to the fact that",
    "one effect of", "one result of",
    "whether", "unless", "even if", "provided that", "on condition that",
    "supposing that", "in case",
    "therefore", "thus", "hence", "consequently", "accordingly",
    "as a result", "as a consequence", "for this reason", "it follows that",
    "so that", "in that case", "under those circumstances", "in such an event",
    "arising out of this", "as a corollary", "apropos", "whereby", "thereby",
    "in a nutshell",
    "however", "though", "although", "yet", "nonetheless", "nevertheless",
    "while", "only", "anyway", "still", "even so", "all the same",
    "at the same time", "in any case", "in any event", "after all",
    "for all that", "in spite of that", "at any rate", "anyhow",
    "another distinction", "else",
    "rather", "instead", "alternatively", "conversely", "on the contrary",
    "on the other hand", "by contrast", "in contrast", "by comparison",
    "in comparison", "by way of contrast", "by way of comparison",
    "a striking difference", "contrariwise", "oppositely",
    "again", "at least",
    "more", "much", "also", "too", "further", "as well", "nor",
    "increasingly", "much more", "in addition", "in particular",
    "what is more", "moreover", "furthermore", "besides", "additionally",
    "apart from that", "aside from this",
    "piece by piece", "cap it", "crown it all", "top it off", 
    "on top of it all", "another interesting aspect",
    "like", "exactly", "similarly", "likewise", "equally",
    "in the same way", "by the same token", "along the same lines",
    "in a similar fashion", "in relation to", "with respect to",
    "with reference to", "in terms of", "in comparison with",
    "in comparison to", "compared with", "compared to", "by comparison with",
    "a different aspect", "ca.", "separate and distinct from",
    "incongruously",
    "such as", "for example", "for instance", "e.g.", "i.e.", "say",
    "namely", "more specifically", "to illustrate",
    "as an illustration", "as an illustration of", "as illustrated by",
    "as revealed by", "the previous example", "the example above",
    "the example below", "a rare example of", "a notable example of",
    "particularly", "that is", "in other words", "to put it another way",
    "to put it differently", "or rather", "better", "more accurately",
    "more precisely", "be exact", "put it mildly", "put it bluntly", 
    "what I mean is",
    "even", "indeed", "certainly", "especially", "the fact that",
    "stress", "emphasize", "significantly", "notably",
    "specifically", "above all", "more importantly", "most importantly",
    "chiefly", "mainly", "primarily", "in the main", "essentially",
    "in essence", "basically", "fundamentally",
    "by all means", "add to that", "regarding", "as to",
    "of critical importance", "of limited value", "in such a manner as",
    "of little significance", "of considerable significance", "of some value",
    "of doubtful value", "of equal weight", "of less significance",
    "of major interest", "of most value", "of overriding importance",
    "of profound importance", "of real value", "of strategic importance",
    "bar none", "the chief characteristics", "the major point",
    "the main issue is", "the most necessary", "of primary concern",
    "right", "well", "you know", "of course", "actually", "I mean",
    "you see", "naturally", "obviously", "clearly", "evidently",
    "manifestly", "undoubtedly", "undeniably", "admittedly", "surely",
    "in fact", "as a matter of fact", "in actual fact",
    "in reality", "in truth", "truly", "really", "according to",
    "it is evident from", "in every aspect", "to be frank", "supposedly",
    "technically speaking", "to be truthful", "what I am saying is",
    "put simply", "OK", "okay", "oh", "mind you", "as I was saying",
    "hypothetically", "comparatively speaking", "practically speaking",
    "academically", "it is an undeniable fact that",
    "generally", "on the whole", "in general", "as a rule",
    "by and large", "for the most part", "in most cases", "in most instances",
    "typically", "normally", "ordinarily", "commonly",
    "as a general rule", "in the majority of cases", "more often than not",
    "in neither case", "with all due respect", "one particular feature",
    "without a shadow of doubt", "the most worrying aspect",
    "the preferred mode of", "the principal characteristics", "up until now",
    "in conclusion", "to conclude", "to sum up",
    "to summarize", "in summary", "in sum", "in brief", "in short",
    "all in all", "overall", "in all", "taking everything into account",
    "taking everything together", "altogether", "resume", "get back to the point"
}

stance_me = {
    "no doubt", "certainly", "undoubtedly", "arguably", "decidedly", 
    "definitely", "incontestably", "incontrovertibly", "of course",
    "probably", "perhaps", "maybe", "most likely", "very likely", 
    "quite likely", "I guess", "I think",
    "in fact", "really", "actually", "in actual fact", "for a fact", "truly",
    "evidently", "apparently", "reportedly", "reputedly",
    "mainly", "typically", "generally", "largely", "in general", "in most cases",
    "in our view", "from our perspective", "in my opinion",
    "like", "literally", "sort of", "about", "kind of", "roughly", 
    "so to speak", "if you can call it that",
    "as might be expected", "inevitably", "as you might guess", "to my surprise",
    "astonishingly", "surprisingly", "predictably",
    "unfortunately", "fortunately", "conveniently", "wisely", "sensibly",
    "quite rightly", "even worse", "disturbingly", "ironically",
    "most surprising of all", "even more importantly", "literally", "seriously", "honestly"
}

reasoning_me = {
    "cause", "lead", "result", "produce", "create", "generate",
    "bring", "yield", "trigger", "induce", "prompt", "contribute",
    "prove", "demonstrate", "show", "indicate", "suggest", "imply",
    "reveal", "illustrate", "establish", "confirm", "verify",
    "substantiate", "corroborate", "evidence",
    "conclude", "infer", "deduce", "reason", "determine", "follow", "entail",
    "argue", "claim", "assert", "contend", "maintain", "hold",
    "posit", "propose", "advance",
    "explain", "account", "justify", "rationalize", "clarify", "elucidate",
    "mean", "signify", "ensure", "guarantee", "necessitate", "require", "dictate"
}

discourse_them = {
    "in case",
    "accordingly",
    "additionally",
    "after",
    "after this",
    "afterward",
    "all in all",
    "also",
    "alternatively",
    "although",
    "and",
    "anyway",
    "as",
    "as a result",
    "as an alternative",
    "as if",
    "as long as",
    "as soon as",
    "as though",
    "as well",
    "assuming that",
    "at any rate",
    "at last",
    "at least",
    "at that",
    "because",
    "before",
    "before and after",
    "besides",
    "but",
    "by comparison",
    "by contrast",
    "by then",
    "consequently",
    "considering that",
    "conversely",
    "earlier",
    "either",
    "either..or",
    "else",
    "except",
    "except in that",
    "except insofar as",
    "finally",
    "for",
    "for example",
    "for instance",
    "from then on",
    "further",
    "furthermore",
    "given that",
    "hence",
    "however",
    "if",
    "if and when",
    "if ever",
    "if only",
    "if..then",
    "immediately",
    "in addition",
    "in conclusion",
    "in contrast",
    "in fact",
    "in other words",
    "in particular",
    "in short",
    "in so doing",
    "in sum",
    "in that",
    "in that case",
    "in the end",
    "in turn",
    "indeed",
    "insofar as",
    "instantly",
    "instead",
    "it follows that",
    "just as",
    "later",
    "lest",
    "likewise",
    "meantime",
    "meanwhile",
    "moreover",
    "much as",
    "neither..nor",
    "nevertheless",
    "next",
    "nonetheless",
    "nor",
    "now that",
    "on condition that",
    "on the contrary",
    "on the grounds that",
    "on the one hand..on the other hand",
    "on the other hand",
    "once",
    "or",
    "or rather",
    "otherwise",
    "overall",
    "plainly",
    "plus",
    "previously",
    "rather",
    "regardless",
    "seeing as",
    "separately",
    "similarly",
    "simultaneously",
    "since",
    "so",
    "so that",
    "specifically",
    "still",
    "summing up",
    "supposing",
    "supposing that",
    "that is",
    "that is to say",
    "the way",
    "then",
    "thereafter",
    "thereby",
    "therefore",
    "though",
    "thus",
    "till",
    "to conclude",
    "to recap",
    "too",
    "ultimately",
    "unless",
    "until",
    "when",
    "when and if",
    "whereas",
    "while",
    "yet",
}

stance_them = {
    "actually",
    "admittedly",
    "alternatively",
    "amazingly",
    "apparently",
    "arguably",
    "astonishingly",
    "certainly",
    "confidentially",
    "conveniently",
    "decidedly",
    "definitely",
    "disturbingly",
    "evidently",
    "figuratively",
    "fortunately",
    "frankly",
    "generally",
    "honestly",
    "hopefully",
    "incontestably",
    "incontrovertibly",
    "indeed",
    "inevitably",
    "ironically",
    "mainly",
    "maybe",
    "only",
    "paradoxically",
    "perhaps",
    "predictably",
    "probably",
    "radically",
    "regrettably",
    "reportedly",
    "reputedly",
    "sensibly",
    "seriously",
    "strictly",
    "supposedly",
    "surprisingly",
    "truly",
    "truthfully",
    "typically",
    "undeniably",
    "undoubtedly",
    "unfortunately",
    "wisely",
}

reasoning_them = {
    "note",
    "accept",
    "accuse",
    "acknowledge",
    "address",
    "admit",
    "advise",
    "affect",
    "afford",
    "agree",
    "allow",
    "announce",
    "answer",
    "appeal",
    "appreciate",
    "approve",
    "argue",
    "ask",
    "assess",
    "assist",
    "assume",
    "assure",
    "bear",
    "believe",
    "blame",
    "bother",
    "calculate",
    "call",
    "care",
    "cause",
    "celebrate",
    "challenge",
    "choose",
    "claim",
    "compare",
    "complain",
    "conclude",
    "confirm",
    "consider",
    "consult",
    "convince",
    "count",
    "dare",
    "decide",
    "declare",
    "demand",
    "deny",
    "describe",
    "deserve",
    "detect",
    "determine",
    "discover",
    "discuss",
    "dismiss",
    "distinguish",
    "doubt",
    "emphasize",
    "enable",
    "encourage",
    "enjoy",
    "ensure",
    "examine",
    "excuse",
    "expect",
    "experience",
    "explain",
    "express",
    "face",
    "fear",
    "feel",
    "find",
    "force",
    "forget",
    "forgive",
    "guarantee",
    "guess",
    "hate",
    "hear",
    "help",
    "hope",
    "identify",
    "ignore",
    "imagine",
    "impress",
    "influence",
    "inform",
    "insist",
    "intend",
    "interpret",
    "invite",
    "judge",
    "justify",
    "know",
    "learn",
    "let",
    "like",
    "listen",
    "love",
    "mean",
    "mention",
    "mind",
    "miss",
    "need",
    "notice",
    "observe",
    "offer",
    "perceive",
    "permit",
    "persuade",
    "phone",
    "plan",
    "pray",
    "predict",
    "prefer",
    "pretend",
    "prevent",
    "promise",
    "propose",
    "prove",
    "publish",
    "question",
    "quote",
    "read",
    "realice",
    "recall",
    "reckon",
    "recognize",
    "recommend",
    "regard",
    "remark",
    "remember",
    "remind",
    "reply",
    "report",
    "require",
    "respond",
    "satisfy",
    "say",
    "see",
    "shout",
    "sign",
    "sing",
    "solve",
    "speak",
    "specify",
    "state",
    "study",
    "suffer",
    "suggest",
    "suppose",
    "suspect",
    "swear",
    "talk",
    "teach",
    "tell",
    "thank",
    "think",
    "threaten",
    "trust",
    "understand",
    "urge",
    "want",
    "warn",
    "welcome",
    "whisper",
    "wish",
    "wonder",
    "worry",
    "write",
}

if __name__ == "__main__":
    intersection_discourse = discourse_me.intersection(discourse_them)
    print("Discourse markers in both lexicons:")
    print(intersection_discourse)

    intersection_stance = stance_me.intersection(stance_them)
    print("\nStance markers in both lexicons:")
    print(intersection_stance)

    intersection_reasoning = reasoning_me.intersection(reasoning_them)
    print("\nReasoning markers in both lexicons:")
    print(intersection_reasoning)
    
    my_discourse_only = discourse_me.difference(discourse_them)
    print("\nDiscourse markers only in my lexicon:")
    print(my_discourse_only)
    
    them_discourse_only = discourse_them.difference(discourse_me)
    print("\nDiscourse markers only in their lexicon:")
    print(them_discourse_only)
    
    my_stance_only = stance_me.difference(stance_them)
    print("\nStance markers only in my lexicon:")
    print(my_stance_only)
    
    them_stance_only = stance_them.difference(stance_me)
    print("\nStance markers only in their lexicon:")
    print(them_stance_only)
    
    my_reasoning_only = reasoning_me.difference(reasoning_them)
    print("\nReasoning markers only in my lexicon:")
    print(my_reasoning_only)

    them_reasoning_only = reasoning_them.difference(reasoning_me)
    print("\nReasoning markers only in their lexicon:")
    print(them_reasoning_only)

    shared_words_across_mine = discourse_me.intersection(stance_me).intersection(reasoning_me)
    print("\nWords that are in all three of my lexicons:")
    print(shared_words_across_mine)
    
    shared_words_across_theirs = discourse_them.intersection(stance_them).intersection(reasoning_them)
    print("\nWords that are in all three of their lexicons:")
    print(shared_words_across_theirs)